spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_pasteleria
    username: postgres
    password: lumia505
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true.
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect			


